times = ('Atlético-MG', 'Palmeiras', 'Fortaleza', 'Bragantino', 'Flamengo', 'Corinthians', 'Atlético-GO', 'Ceará', 'Atlético-PR', 'Internacional', 'Santos', 'São Paulo', 'Juventus', 'Cuiaba', 'Bahia', 'Fluminense', 'Gremio', 'Sport', 'America-MG', 'Chapecoense')
print('Os 5 primeros times são: ')
print(times[0:5])
print('-=-' *25)
print('Os 4 ultimos são: ')
print(times[-4:])
print('-=-'*25)
print('Times em ordem alfabética:')
print(sorted(times))
print('-=-'*25)
print('O time da chapecoense esta na posição: ')
print(times.index('Chapecoense')+1)
